name: APTGET-Blog
title: "[APTGET]"
description: "DevOps, Data und Programmierung"
logo: /assets/images/logo.jpg

#markdown: redcarpet
markdown: kramdown
pygments: true

comments: true
paginate: 0
paginate_path: "/page:num"
permalink: /:title.html
#plugins: [jekyll-paginate]
